version: "3.5"
services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - mariadb
      - wordpress
      # - adminer
    container_name: nginx
    restart: unless-stopped
    volumes:
      - vwp:/var/www/html
    networks:
      - 13_network

  wordpress:
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress
    env_file: ./.env
    restart: unless-stopped
    networks:
      - 13_network
    volumes:
      - vwp:/var/www/html

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    env_file:
      - ./.env
    networks:
      - 13_network
    container_name: mariadb
    restart: unless-stopped
    # volumes:
    #   - vmd:/var/lib/mysql
  
volumes:
  vwp:
    driver_opts:
      type: none
      o: bind
      device: /home/root/inception/data/wordpress
  vmd:
    driver_opts:
      type: none
      o: bind
      device: /home/root/inception/data/mariadb
      
networks:
  13_network:
    driver : bridge

