                                  # ================================== #
                                  # 2.COPY PROJECT - copy-project.yaml #
                                  # ================================== #
- hosts: all
  become: yes
  tasks:
    - name: Create project directory
      file:
        path: /home/{{ ansible_user }}/inception
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy project files
      copy:
        src: ../inception/
        dest: /home/{{ ansible_user }}/inception/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    
    - name: Set DOMAIN_NAME in .env to the host's IP address
      lineinfile:
        path: /home/{{ ansible_user }}/inception/srcs/.env
        regexp: '^DOMAIN_NAME='
        line: "DOMAIN_NAME={{ ansible_host }}"
